routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
Route::get('checkSession','HomeController@checkSession');

Route::middleware('auth')->group(function()
{
    Route::get('/',function()
    {
        if(Auth::user()->hasRole('admin'))
        {        
            return redirect('/admin');
        }
        if(Auth::user()->hasRole('doctor'))
        {        
            return redirect('/doctor');
        }
        if(Auth::user()->hasRole('pharmacist'))
        {        
            return redirect('/pharmacy');
        }
        if(Auth::user()->hasRole('laboratorist'))
        {        
            return redirect('/laboratory');
        }
        if(Auth::user()->hasRole('receptionist'))
        {        
            return redirect('/reception');
        }
    });

    Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function()
    {
        Route::get('/admin','AdminController@index');
        Route::get('/admin/patients/list',function(){
            $title = 'Ádmininstrator :: Patients';
            return view('admin.patient',compact('title'));
        });
        Route::get('/admin/appointment/list',function(){
            $title = 'Ádmininstrator :: Appointments';
            return view('admin.appointment',compact('title'));
        });
        Route::get('/admin/appointment/upcoming',function(){
            $title = 'Ádmininstrator :: Upcoming Appoinment';
            return view('admin.upcoming',compact('title'));
        });
        Route::get('/admin/medicine/list',function(){
            $title = 'Ádmininstrator :: Medicine';
            return view('admin.medicine',compact('title'));
        });
        Route::get('/admin/billing/list',function(){
            $title = 'Ádmininstrator :: Billings';
            return view('admin.billing',compact('title'));
        });
        Route::get('/admin/services',function(){
            $title = 'Ádmininstrator :: Services';
            return view('admin.service',compact('title'));
        });
        Route::get('/admin/servicemodes',function(){
            $title = 'Ádmininstrator :: Service Modes';
            return view('admin.servicemode',compact('title'));
        });
        Route::get('/admin/users',function(){
            $title = 'Ádmininstrator :: Users';
            return view('admin.users',compact('title'));
        });
        Route::get('/admin/settings',function(){
            $title = 'Ádmininstrator :: Settings';
            return view('admin.settings',compact('title'));
        });
        Route::get('/admin/rooms',function(){
            $title = 'Ádmininstrator :: Rooms';
            return view('admin.room',compact('title'));
        });
        Route::get('/admin/units',function(){
            $title = 'Ádmininstrator :: Unit Allocations';
            return view('admin.units',compact('title'));
        });

        Route::post('/admin/user/create','AdminController@addUser');
        Route::post('/admin/user/update','AdminController@updateUser');
        Route::post('/admin/room/create','AdminController@addRoom');
        Route::post('/admin/room/update','AdminController@updateRoom');
        Route::post('/admin/service/create','AdminController@addService');
        Route::post('/admin/service/update','AdminController@updateService');
        Route::post('/admin/servicemode/create','AdminController@addServiceMode');
        Route::post('/admin/servicemode/update','AdminController@updateServiceMode');
        Route::post('/admin/unit/create','AdminController@addUnit');
        Route::post('/admin/unit/update','AdminController@updateUnit');

    });

    Route::group(['middleware' => 'App\Http\Middleware\DoctorMiddleware'], function()
    {
        Route::get('/doctor', 'DoctorController@index');
        Route::get('/doctor/appointments','AppointmentController@index');
        Route::get('/doctor/patients', 'PatientsController@index');
        Route::get('/doctor/patient/view/{reg_no}', 'PatientsController@view');
        Route::get('/doctor/patient/history/{reg_no}', 'PatientsController@history');
        Route::get('/doctor/patient/history/view/{reg_no}/{id}', 'PatientsController@history_view');

    });

    Route::group(['middleware' => 'App\Http\Middleware\PharmacyMiddleware'], function()
    {
        Route::get('/pharmacy','PharmacyController@index');
        //billings
        Route::get('/pharmacy/billings', 'BillingController@pharmacyBilling');
        Route::get('/pharmacy/prescription','BillingController@prescriptionBilling');

    });

    Route::group(['middleware' => 'App\Http\Middleware\LabMiddleware'], function()
    {
        Route::get('/laboratory','LaboratoryController@index');

    });

    Route::group(['middleware' => 'App\Http\Middleware\ReceptionMiddleware'], function()
    {
        Route::get('/reception', 'PatientsController@index'); 
        Route::get('/reception/patients','PatientsController@index');
        Route::get('/reception/patient/edit/{reg_no}', 'PatientsController@edit');
        Route::get('/reception/patient/view/{reg_no}', 'PatientsController@view');

        Route::get('/reception/appointments','AppointmentController@index');        
        Route::get('/reception/appointment/edit/{id}', 'AppointmentController@edit');

        Route::get('/reception/billing', 'BillingController@index');       

    });


    Route::get('/photo','PatientsController@photo');
    
    Route::resource('patients', 'PatientsController');

    Route::get('/patient/visit','PatientsController@visit');
    Route::get('/patient-que/delete/{id}','PatientsController@delete_que');

    Route::get('/patientQue','DatatableController@patient_que');
    Route::get('/patientDocQue','DatatableController@doc_patient_que');
    Route::get('/patientHistory/{id}','DatatableController@patient_history');
    Route::get('/patientList','DatatableController@patient_list');
    Route::get('/patientPayment/{id}','DatatableController@patient_payment');

    Route::resource('appointments', 'AppointmentController');
    Route::get('/appointment/edit/{id}','AppointmentController@edit');

    Route::get('/appointmentUpcoming','DatatableController@upcoming_appointment');
    Route::get('/appointmentList','DatatableController@appointment_list');
    Route::get('/appointmentDoc','DatatableController@doc_appointment');

    Route::resource('billings','BillingController');
    Route::get('/billing/list','DatatableController@billingList');
    Route::get('/billing/medicine','DatatableController@billingMedicine');
    Route::get('/billing/lab','DatatableController@billingLab');
    Route::get('/billing/patient','DatatableController@billingPatient');
    Route::get('/billing/reception','DatatableController@billingReception');

    Route::get('/autocomplete/{id}','Patients@autocomplete_ajax');
    Route::get('/name-ajax','PatientsController@name_ajax');
    Route::get('/getRegNo','PatientsController@generatePatientRegNo');
    Route::get('/getAge','PatientsController@getAge');

    Route::get('/getCharges/{id}','AppointmentController@getCharges');

    Route::get('/users','DatatableController@users');
    Route::get('/rooms','DatatableController@rooms');
    Route::get('/services','DatatableController@services');
    Route::get('/servicemodes','DatatableController@servicemodes');
    Route::get('/units','DatatableController@units');

});

app/Billing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Billing extends Model
{
    protected $date = ['created_at'];
    protected $primaryKey = 'billing_id';
}

app/Http/Controllers/BillingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Billing;
use DB;

class BillingController extends Controller
{
    public function index()
    {
        $title = 'Reception :: Payments';
        return view('reception.billing',compact('title'));
    }

    public function pharmacyBilling()
    {
        $title = 'Pharmacy :: Payments';
        return view('billings.index',compact('title'));
    }

    public function prescriptionBilling()
    {
        $title = 'Pharmacy :: Prescriptions';
        return view('pharmacy.prescription',compact('title'));
    }

    public function store(Request $reaquest)
    {
        $billing = new Billing;
        $billing->transaction_id = $request->transaction_id;
        $billing->patient_reg_no = $request->patient_reg_no;
        $billing->service_id = $request->service_id;
        $billing->amount = $request->amount;
        $billing->amount_paid = $request->amount_paid;
        $billing->amount_due = float_val($request->amount) - float_val($request->dicount);
        $billing->discount = $request->discount;

        $billing->save();

    }

    public function update($id, Request $request)
    {
        $billing = Billing::find($id);
        $billing->transaction_id = $request->transaction_id;
        $billing->patient_reg_no = $request->patient_reg_no;
        $billing->service_id = $request->service_id;
        $billing->amount = $request->amount;
        $billing->amount_paid = $request->amount_paid;
        $billing->amount_due = float_val($request->amount) - float_val($request->dicount);
        $billing->discount = $request->discount;

        $billing->save();
    }

    public function delete($id)
    {
        Billing::destroy($id);
    }

    public function transactionId()
    {
        $nextId = DB::select("show table status like 'billings'");
        $trans_id = 'PAY-'.timestamp().'-'.sprintf("%02d", $nextId[0]->Auto_increment);
        return $trans_id;
    }
}

resources/views/billings/create.blade.php
<!-- modal edit Category -->
<div class="modal fade" id="payBill" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="largeModalLabel">Make Payment</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
            <form id="billing-create" enctype="multipart/form-data" method="post" action="{{ route('billings.store') }}" >
                {{ csrf_field() }}
				<div class="modal-body">
					<div class="row form-group">
						<div class="col-md-6">
							<p>Transaction ID: <span></span></p>
							<input type="text" name="transaction_id" id="transaction_id" hidden>
                        </div>
                        <div class="col-md-6">
							<p>Patient Reg. #: <span></span></p>
							<input type="text" name="patient_reg_no" id="patient_reg_no" hidden>
                        </div>
                        <div class="col-md-12">
							<p>Requested Service: <span></span></p>
							<input type="text" name="service_id" id="service_id" hidden>
						</div>
                        <div class="col-md-12">
							<p>Service Charge: <span></span></p>
							<input type="text" name="amount" id="amount" hidden>
						</div>
						<br/><br/><br/>
						<div class="col-md-6">
							<div class="form-group">
                                <label for="description" class=" form-control-label">Amount</label>
                                <div class="input-group">
                                    <div class="input-group-addon">TZS
                                    </div>
                                    <input type="number" id="amount_paid" name="amount_paid" class="form-control" value="0" min="0">
                                </div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label for="description" class=" form-control-label">Discount</label>
								<div class="input-group">
									<div class="input-group-addon">TZS
									</div>
									<input type="number" id="discount" name="amount" class="form-control" value="0" min="0">
								</div>
							</div>
						</div>						
					</div>
					<br>
					{{-- <strong class="pull-right text-right">Amount Paid: TZS 7900</strong><br />
					<strong class="pull-right text-right">Amount Due: TZS 7900</strong><br /> --}}
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary">Confirm</button>
				</div>
            </form>
		</div>
	</div>
</div>
<!-- end edit Category -->

resources/views/billings/edit.blade.php
<!-- modal edit Category -->
<div class="modal fade" id="editPayment" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="largeModalLabel">Payment Edit</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
            <form id="billing-update" enctype="multipart/form-data" method="post" action="" >
                {{ csrf_field() }}
				<div class="modal-body">
					<div class="row form-group">
						<div class="col-md-6">
							<p>Transaction ID: <span></span></p>
							<input type="text" name="transaction_id" id="transaction_id" hidden>
						</div>
						<div class="col-md-6">
							<p>Patient Reg. #: <span></span></p>
							<input type="text" name="patient_reg_no" id="patient_reg_no" hidden>
						</div>
						<div class="col-md-12">
							<p>Requested Service: <span></span></p>
							<input type="text" name="service_id" id="service_id" hidden>
						</div>
						<div class="col-md-12">
							<p>Service Charge: <span></span></p>
							<input type="text" name="amount" id="amount" hidden>
						</div>
						<br/><br/><br/>
						<div class="col-md-6">
							<div class="form-group">
								<label for="description" class=" form-control-label">Amount</label>
								<div class="input-group">
									<div class="input-group-addon">TZS
									</div>
									<input type="number" id="amount_paid" name="amount_paid" class="form-control" value="0" min="0">
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label for="description" class=" form-control-label">Discount</label>
								<div class="input-group">
									<div class="input-group-addon">TZS
									</div>
									<input type="number" id="discount" name="amount" class="form-control" value="0" min="0">
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary">Confirm</button>
				</div>
            </form>
		</div>
	</div>
</div>
<!-- end edit Category -->

resources/views/billings/index.blade.php
@extends('home')
@section('section')
<div class="default-tab">
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="payment-list-tab" data-toggle="tab" href="#payment-list" role="tab" aria-controls="payment-list"
        aria-selected="true" ><i class="fas fa-list"></i> All Payments</a>
  
        <a class="nav-item nav-link" id="lab-bill-tab" data-toggle="tab" href="#lab-bill" role="tab" aria-controls="lab-bill"
        aria-selected="false"><i class="fas fa-list"></i> Lab Queue Billing</a>
  
        <a class="nav-item nav-link" id="patient-bill-tab" data-toggle="tab" href="#patient-bill" role="tab" aria-controls="patient-bill"
        aria-selected="false"><i class="fas fa-list"></i> Patient Billings</a>
      </div>
    </nav>
    <div class="tab-content pl-3 pt-2" id="nav-tabContent">
  
      <div class="tab-pane fade show active" id="payment-list" role="tabpanel" aria-labelledby="payment-list-tab">
        @include('billings.list')
      </div>
  
      <div class="tab-pane fade" id="lab-bill" role="tabpanel" aria-labelledby="lab-bill-tab">
        @include('billings.lab-bill')
      </div>

      <div class="tab-pane fade" id="patient-bill" role="tabpanel" aria-labelledby="patient-bill-tab">
        @include('billings.patient-bill')
      </div>
  
    </div>
  </div>
  @endsection

resources/views/billings/lab-bill.blade.php
  <!-- DATA TABLE-->
  <section class="p-t-20">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="title-5 m-b-35">Lab Tests Payments</h3>

                <div class="row">
                    <div class="col-md-12">
                        <!-- DATA TABLE-->
                        <div class="table-responsive m-b-40">
                            <table id="lab-billing" class="table datatable-1 table-borderless table-data3">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Reg. #</th>
                                        <th>Name</th>      
                                        <th>Service Requested</th>
                                        <th>Doctor</th>
                                        <th>Amount</th>
                                        <th>Amount Paid</th>
                                        <th>Amount Due</th>
                                        <th>Discount</th>
                                        <th>Waiting Time</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                        <!-- END DATA TABLE                  -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END DATA TABLE-->

resources/views/billings/list.blade.php
  <!-- DATA TABLE-->
  <section class="p-t-20">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="title-5 m-b-35">List of Payments</h3>

                <div class="row">
                    <div class="col-md-12">
                        <!-- DATA TABLE-->
                        <div class="table-responsive m-b-40">
                            <table id="billing-list" class="table table-borderless table-data3">
                                <thead>
                                    <tr>
                                        <th>Transaction #</th>
                                        <th>Date</th>
                                        <th>Reg. #</th>
                                        <th>Name</th>      
                                        <th>Service Requested</th>
                                        <th>Doctor</th>
                                        <th>Amount</th>
                                        <th>Amount Paid</th>
                                        <th>Amount Due</th>
                                        <th>Discount</th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                        <!-- END DATA TABLE                  -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END DATA TABLE-->

resources/views/billings/patient-bill.blade.php
  <!-- DATA TABLE-->
  <section class="p-t-20">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="title-5 m-b-35">Patient Medicine &amp; Service Payments</h3>

                <div class="row">
                    <div class="col-md-12">
                        <!-- DATA TABLE-->
                        <div class="table-responsive m-b-40">
                            <table id="patient-billing" class="table table-borderless table-data3">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Reg. #</th>
                                        <th>Name</th>      
                                        <th>Service Requested</th>
                                        <th>Doctor</th>
                                        <th>Amount</th>
                                        <th>Amount Paid</th>
                                        <th>Amount Due</th>
                                        <th>Discount</th>
                                        <th>Waiting Time</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                        <!-- END DATA TABLE                  -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END DATA TABLE-->

resources/views/billings/prescription.blade.php
  <!-- DATA TABLE-->
  <section class="p-t-20">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="title-5 m-b-35">Medicine Prescriptions Payment</h3>

                <div class="row">
                    <div class="col-md-12">
                        <!-- DATA TABLE-->
                        <div class="table-responsive m-b-40">
                            <table id="medicine-billing" class="table datatable-1 table-borderless table-data3">
                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Patient Name</th>      
                                        <th>Medicine</th>
                                        <th>Doctor</th>
                                        <th>Amount</th>
                                        <th>Amount Paid</th>
                                        <th>Amount Due</th>
                                        <th>Discount</th>
                                        <th>Waiting Time</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                        <!-- END DATA TABLE                  -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END DATA TABLE-->

resources/views/billings/view.blade.php
<!-- modal edit Category -->
<div class="modal fade" id="editMedCategory" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="largeModalLabel">Payment Details</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
            <form enctype="multipart/form-data" method="post" action="" >
                {{ csrf_field() }}
				<div class="modal-body">
					<div class="row form-group">
                        <div class="col-md-4">
                            <p>Date: <span></span></p>
                        </div>
						<div class="col-md-4">
							<p>Transaction ID: <span></span></p>
                        </div>
                        <div class="col-md-4">
                            <p>Requested Service: <span></span></p>
                        </div>
                        <div class="col-md-6">
							<p>Patient Reg. #: <span></span></p>
                        </div>
                        <div class="col-md-6">
                            <p>Patient Name: <span></span></p>
                        </div>
                        
                        <strong class="pull-right">Amount Due: TZS 7900</strong><br />
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
					<button type="submit" class="btn btn-primary">Confirm</button>
				</div>
            </form>
		</div>
	</div>
</div>
<!-- end edit Category -->